from deep_translator import GoogleTranslator
import epitran
de = input("Was ist das Wort in Deutsch? > ")
print("------")
print("----")
en = GoogleTranslator(source='auto', target='en').translate(de)
print("O---")
id = GoogleTranslator(source='auto', target='id').translate(de)
print("OO--")
it = GoogleTranslator(source='auto', target='it').translate(de)
print("OOO-")
pl = GoogleTranslator(source='auto', target='pl').translate(de)
print("OOOO")
ru = GoogleTranslator(source='auto', target='ru').translate(de)
print("■-----")
ger = epitran.Epitran('deu-Latn')
ipager = ger.transliterate(de)
print("■■----")
ind = epitran.Epitran('ind-Latn')
ipaind = ind.transliterate(id)
print("■■■---")
ita = epitran.Epitran('ita-Latn')
ipaita = ita.transliterate(it)
print("■■■■--")
pol = epitran.Epitran('pol-Latn')
ipapol = pol.transliterate(pl)
print("■■■■■-")
rus = epitran.Epitran('rus-Cyrl')
iparus = rus.transliterate(ru)
print("■■■■■■")
print(f'Deutsch: {de} [{ipager}]')
print(f'Englisch: {en} [???]')
print(f'Indonesisch: {id} [{ipaind}]')
print(f'Italienisch: {it} [{ipaita}]')
print(f'Polnisch: {pl} [{ipapol}]')
print(f'Russisch: {ru} [{iparus}]')